### ISSUE TITLE
Problemas con Gradle 7.0

### ISSUE THREAD

**Issue by coboja84** [bancolombia/scaffold-clean-architecture#148]
Al utilizar la versión 7.0 de Gradle la creación del proyecto funciona bien, sin embargo, al intentar crear un Entrypoint, o un caso de uso, o un modelo sale el siguiente error,

> FAILURE: Build failed with an exception.
> Where:
> Build file '[project]\applications\app-service\build.gradle' line: 6

> What went wrong:
> A problem occurred evaluating project ':app-service'.
> Could not find method compile() for arguments [org.springframework.boot:spring-boot-starter] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by santitigaga** [comment]
Hola en la versión de gradle 7.0 diferentes  instrucciones entre ellas compile han sido removidas del APi disponible. estaremos ajustando el plugin en el próximo release para que sea compatible con gradle 7 y las versiones anteriores. 

Sin embargo para que puedas seguir usando  el plugin sin inconvenientes  te recomendamos hacer lo mismo con el wrapper de gradle.

Lo puedes generar con la siguiente instrucción:
```
gradle wrapper
```
ya con esto puedes crear el entrypoint de la siguiente forma:
```
./gradlew generateEntryPoint ...
```
