### ISSUE TITLE
Include the "UseCase" Word

### ISSUE THREAD

**Issue by juanes1a** [bancolombia/scaffold-clean-architecture#20]
It´s a bit confusing when you create an use case because it is not clear if in the name has to include or not the word "UseCase" so it'll be helpful if when you create an use case and the plugin automatically add the word UseCase to it, example if i generate the use case Person, the final result would be a class with name PersonUseCase. This would help us to keep classes naming standard

**Comment by santitigaga** [comment]
Fix in release 1.5.2
