### ISSUE TITLE
Error on Jar generation app-service

### ISSUE THREAD

**Issue by VManuelPM** [bancolombia/scaffold-clean-architecture#26]
When The build is generating from gradle of app-service it doesn't create the folder libs into this

app-service/build/libs 

The possible solution is replace the task jar for the next: 

task explodedJar(type: Copy) {
    with jar
    into "${buildDir}/exploded"
}

For more details contact me: 

My corporate email -->  vpedraza@bancolombia.com.co

**Comment by santitigaga** [comment]
Hi Victor,

You are ok, in the next version will be fixed.

Regards.
