### ISSUE TITLE
Add configuration parameter to indicate spring boot track

### ISSUE THREAD

**Issue by gabheadz** [bancolombia/scaffold-clean-architecture#314]
**Is your feature request related to a problem? Please describe.**
Define a configuration flag to indicate to the `ca` task which track of spring-boot to use.

**Describe the solution you'd like**
**If and only if we decide to provide this level of configuration**, then I would imagine a parameter like this:

```bash
gradlew ca --package=com.example.demo --type=reactive --name=demo --coverage=jacoco --lombok=true --bootVersion=VERSION_2
```

or 

```bash
gradlew ca --package=com.example.demo --type=reactive --name=demo --coverage=jacoco --lombok=true  --bootVersion=VERSION_3
```

if `bootVersion=VERSION_3` is selected, then `javaVersion` should be automatically defined as JAVA_17

**Describe alternatives you've considered**

One alternative is to keep the scaffolder versions up to 2.x.x using spring-boot 2.7.x and produce a new major version of the scaffolder 3.x fixed for spring boot 3.x.

**Comment by juancgalvis** [comment]
Hi @gabheadz, I think that we should only support the latest release of Spring Boot, what do you think @dbuos @santitigaga @maocq?

**Comment by santitigaga** [comment]
I think the same.
If consumer use the plugin version 3.x we could generate the project with spring boot 3. or if you use the plugin version 2.x we could generate the project with spring boot 2.

We might need to change something in the previous version (2.x). we can do this with a branch to update this version.

**Comment by juancgalvis** [comment]
It will not be implemented
