### ISSUE TITLE
Problema al generar el jar

### ISSUE THREAD

**Issue by enterpreneur369** [bancolombia/scaffold-clean-architecture#464]
**Is your feature request related to a problem? Please describe.**
Cuando se usa el comando gradle clean build cuando se intenta ejecutar el jar directamente con el comando java -jar archivo

Este no funciona y revisando el manifest indica que no tiene una clase main.

**Describe the solution you'd like**
Me gustaría poder ejecutar el artefacto jar directamente desde la consola, no solo desde el ide.

**Describe alternatives you've considered**
He intentado agregar lineas relacionadas con el manifest en el build.gradle de la página principal

**Additional context**
Estoy usando java 21

**Comment by juancgalvis** [comment]
Hi @enterpreneur369, 

Sometimes this error is caused by a mistake on jar location or in gradle settings.

Please check which jar are you trying to run.

The app jar is located at: applications/app-service/build/libs/<projectName>.jar

```bash
java -jar applications/app-service/build/libs/cleanArchitecture.jar
```

**Comment by enterpreneur369** [comment]
Es que ese el problema, no se puede ejecutar el jar asi lo exporte.
