### ISSUE TITLE
Error al arrancar proyecto

### ISSUE THREAD

**Issue by enterpreneur369** [bancolombia/scaffold-clean-architecture#494]
**Is your feature request related to a problem? Please describe.**
Al arrancar un nuevo proyecto en windows con el comando en java 17 termutin en el ide IJ si se accede a la clase main y se intenta compilar sale un error "java.lang.IllegalStateException: Module entity with name: <nombre_proyecto> should be available"

**Describe the solution you'd like**
Me gustaría que me permitiera compilar el proyecto base

**Describe alternatives you've considered**
He intentado cambiar las versiones de java entre la 21 y la 17 pero el error es el mismo.

**Comment by juancgalvis** [comment]
Please follow our [documentation page](https://bancolombia.github.io/scaffold-clean-architecture/docs/getting-started)
