### ISSUE TITLE
Update reactive-commons version

### ISSUE THREAD

**Issue by favelezr94** [bancolombia/scaffold-clean-architecture#56]
On current version (1.5.4), the plugin is using an old version of reactive commons.

![image](https://user-images.githubusercontent.com/64857454/83426749-3d5c5e00-a3f5-11ea-8780-7f02085c1660.png)

It would be better if you update it to a recent version.

**Comment by juancgalvis** [comment]
Also applies to the spring boot version, version will be updated to 2.2.8.RELEASE
