### ISSUE TITLE
Reactive commons domain model interface mismatch

### ISSUE THREAD

**Issue by favelezr94** [bancolombia/scaffold-clean-architecture#57]
At the current version (1.5.4). When you try to do a:

`gradle gda --value 3`

The structure created has the following error.
![image](https://user-images.githubusercontent.com/64857454/83428386-e60bbd00-a3f7-11ea-8f10-dcaa9c280586.png)
It has a mismatch with the interface created at that path and it does not contain the "emit" method as well.
![image](https://user-images.githubusercontent.com/64857454/83428551-36831a80-a3f8-11ea-9ee5-4d8105b4efe9.png)

**Comment by santitigaga** [comment]
Solved in pull request #65
