### ISSUE TITLE
No es posible implementar paginación en un proyecto webflux?

### ISSUE THREAD

**Issue by enterpreneur369** [bancolombia/scaffold-clean-architecture#574]
**Is your feature request related to a problem? Please describe.**
Hola, estoy intentando crear paginación en un proyecto pero al agregar la dependencia en el main.gradle se daña la arquitectura por el validador del proyecto:
Esto me muestra al arrancar el proyecto.
Validating Model Module
--- Dependency: reactor-core
--- Dependency: reactor-extra
--- Dependency: spring-data-commons
--- Dependency: spring-boot-dependencies
--- Dependency org.springframework.data:spring-data-commons is not allowed in Model Layer

**Describe the solution you'd like**
No entiendo cual es la manera correcta de implementar paginación si no es posible poner el Page en el caso de uso.

**Describe alternatives you've considered**
Me podrían aclarar si esto es un error de la validación o se aborda de forma diferente.

**Comment by santitigaga** [comment]
@enterpreneur369  All dependencies defined in `main.gradle` are ependencies that can be used in any layer. in this case this dependency would be used in infrastructure layer.
 regards
