### ISSUE TITLE
Tarea gradle para generar reporte cobertura con jacoco

### ISSUE THREAD

**Issue by CarlosM4rtinez** [bancolombia/scaffold-clean-architecture#77]
Hola!, seria interesante que el scaffold de clean architecture venga ya configurado con la tarea jacoco de gradle para generar el reporte de cobertura de pruebas con todo el consolidado de los módulos del proyecto.

`task jacocoRootReport(type: JacocoReport){
    
    dependsOn = subprojects.test
    additionalSourceDirs.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    sourceDirectories.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    classDirectories.setFrom files(subprojects.sourceSets.main.output)
    executionData.setFrom project.fileTree(dir: '.', include: '**/build/jacoco/test.exec')

    reports {
        html.enabled = true
        html.destination = file("${buildDir}/jacoco")
        xml.enabled = true
        xml.destination = file("${buildDir}/jacoco/report.xml")
        csv.enabled = false
    }
    
}`

**Comment by santitigaga** [comment]
Hi @CarlosM4rtinez , you can use jacoco or cobertura in your project. You need generated the scaffold with the option _coverage = <jacoco | cobertura>_ if you dont specify the coverage tool, the default value is jacoco.

Maybe is usefull generate the pipeline too  with the task _gradle generatePipeline --type=[pipelineType]_ that use the report of the coverage tool and publish with sonarQube.
