### ISSUE TITLE
Add Github Actions in pipelines as a code

### ISSUE THREAD

**Issue by santitigaga** [bancolombia/scaffold-clean-architecture#92]
Add new option in the Generate Pipeline Task ,can follow azure pipeline option to generate that.

**Comment by varunvjha** [comment]
Hey, could you state what all exactly do you need in this code?

**Comment by santitigaga** [comment]
> 
> 
> Hey, could you state what all exactly do you need in this code?

Of course @varunvjha, the plugin has a task to generate pipelines as a code, today only has the azure pipeline option, it will be great than add new options like github action, travis, jenkins, etc. All the pipeline options should have task to Continious Integration and Continious Deployment as azure option.
