### ISSUE TITLE
Use Application Server Undertow when generating an imperative structure

### ISSUE THREAD

**Issue by santitigaga** [bancolombia/scaffold-clean-architecture#94]
By default spring-boot-starter-web use Tomcat application server, we want to generate projects using undertow application server.

**Comment by D-Jurado** [comment]
The parameter to define the server should be part of the command to create the structure?

**Comment by santitigaga** [comment]
Hi @D-Jurado, really we want to add this parameter in task generate driven Adapter, when the user select  the type restmvc.

**Comment by D-Jurado** [comment]
> Hi @D-Jurado, really we want to add this parameter in task generate driven Adapter, when the user select the type restmvc.

Roger that. I'm on it
