### ISSUE TITLE
LocalContainerEntityManagerFactoryBean cannot resolve setPackagesToScan

### ISSUE THREAD

**Issue by juanes1a** [bancolombia/scaffold-clean-architecture#96]
When i'm using the plugin i generated the structure without problem, but when you import the generic jpa driven adapter there is some missing dependendcies like:
compile 'com.zaxxer:HikariCP:3.4.5'
compile group: 'org.springframework', name: 'spring-orm', version: '2.5.1'

This dependencies should go in the app-service layer on the build.gradle file. Also when you import the missing dependencies the method setPackagesToScan it seems to have no implementation for LocalContainerEntityManagerFactoryBean object in Jpaconfig file

**Comment by juancgalvis** [comment]
To fix it, you should change implementation for compile in build.gradle of jpa-repository module

compile 'org.springframework.boot:spring-boot-starter-data-jpa'

We are working on a new release fixing it.

Duplicated: #95
